version: '3.8'

services:
  ozos:
    container_name: ozos-prd
    build: .
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=production
      - VIRTUAL_HOST=ozos.com.br
      - LETSENCRYPT_HOST=ozos.com.br
      - LETSENCRYPT_EMAIL=gabrielc.machado@hotmail.com
      - VIRTUAL_PORT=3000
      - NODE_ENV=production
    networks:
      - nginx-net
    restart: always
    labels:
      - "com.github.nginx-proxy.container=true"
networks:
  nginx-net:
    external: true
